openapi: 3.1.0
info:
  version: 1.0.0
  title: Yuliia-Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://127.0.0.1:3000
  - url: http://localhost:3000
  - url: https://contacts-app-x92j.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    put:
      $ref: ../swagger/paths/contacts/{id}/put.yaml
  #Auth:
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
  /auth/request-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email/post.yaml
  /auth/reset-password:
    post:
      $ref: ../swagger/paths/auth/reset-password/post.yaml
  #Auth/Google:
  /auth/google/get-oauth-url:
    get:
      $ref: ../swagger/paths/auth/google/get.yaml
  /auth/google/confirm-oauth:
    post:
      $ref: ../swagger/paths/auth/google/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
